### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by immesys** [ucb-bar/asyncqueue-lite#1]
I get the following warning when I use this:
```
[deprecated] class freechips.asyncqueue.CrossingIO (1 calls): Unable to automatically infer cloneType on class freechips.asyncqueue.CrossingIO: constructor has parameters (gen) that are not both immutable and accessible. Either make all parameters immutable and accessible (vals) so cloneType can be inferred, or define a custom cloneType method.
```
Is there something I am doing wrong? I am instantiating as follows:

```
val fifo = Module(new AsyncQueue(UInt(16.W), AsyncQueueParams(256)))
```

**Comment by edwardcwang** [comment]
Thanks for your interest in the AsyncQueue library! As a user, it's safe to ignore the warning. Your instantiation of the AsyncQueue looks fine to me. Please feel free to re-open the issue if you continue to experience problems.

**Comment by immesys** [comment]
Thank you for the fast response.
